### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by Chimera16** [avstudnitz/AvS_FastSimpleImport#212]
I have a empty product catalog, and 17 scripts. Each script import 10.000 products. 

Now I can only run one of them. It works perfect. But:

After I finished the first script, every script gives me a not enough memory error.

If I clear my complete product catalog, every script will work fine again until I import the next 10.000... 

Why does the success of a script depends on how much products I have in my product catalog?

Thank you in advance!

**Comment by paales** [comment]
@Chimera16 When running an import, the importer loads all SKU's and categories before importing. Loading 10k SKU's takes memory. How much memory have you allocated? For 10k SKU's it is advised to have at least a gig of memory available for the importer because all the indexers take a lot of memory as well.

**Comment by Chimera16** [comment]
@paales Thank you for your answer! Is there a Way to import without using this huge amount of memory? I would like to run a Shop with 175.000 products... Right now I have one gig of memory...

**Comment by Chimera16** [comment]
how much memory do I need for 175k products?

**Comment by paales** [comment]
We are running 500k products under a gig of memory with Magento CE, so you should be ok.

**Comment by Chimera16** [comment]
@paales Thank you very much for your help! :+1:

**Comment by paales** [comment]
No problem!
