### ISSUE TITLE
Problems with same option in capital or normal letters not case sensitive

### ISSUE THREAD

**Issue by cfroe** [avstudnitz/AvS_FastSimpleImport#233]
Andreas,

I'm happy to use your extension. Our customer has a large old database cleaning up right now. So in the first import we had a multiselect attribute "TRACTOR" now they changed to "Tractor". So now 2 similar options exist and it looks like while importing the result is just random which option is taken. As I found in the Function "prepareAttributesForSave" you use strtolower for the option and in the array _attributes all options are already converted with strtolower and there is only 1 option "tractor" instead of 2.

Is there a reason why setting values with options it's not possible to do that case sensitive? I didn't find right away where and how the options are loaded and perhaps converted?

You can also answer in german if you want to. Thanks in advance

Christoph

**Comment by paales** [comment]
@cfroe Confirmed, in Magento attribute values are case insensitive, but the auto-creation of the attribute values are case sensitive. 

This comparison should strtolower every values:
https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L213-L217
https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L246-L250

**Comment by sprankhub** [comment]
@paales I would like to solve this and this should be quite straightforward. I am more than happy to provide a pull request if you help me to decide between the two options we have:

1. **Converting the attribute labels to lower case on-the-fly.**
  1. https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L243 / https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L276

    OLD: `if (!in_array(trim($rowData[$attributeCode]), $options, true)) {`

    NEW:

        $options = array_map('strtolower', $options);
        if (!in_array(strtolower(trim($rowData[$attributeCode])), $options, true)) {

2. **Changing `_getAttributeOptions` to return lower-case option labels and search.**
  1. https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L304

    OLD: `$this->_attributeOptions[$attribute->getAttributeCode()][$option['value']] = $option['label'];`

    NEW: `$this->_attributeOptions[$attribute->getAttributeCode()][$option['value']] = strtolower($option['label']);`

  2. https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L243 / https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L276

    OLD: `if (!in_array(trim($rowData[$attributeCode]), $options, true)) {`

    NEW: `if (!in_array(strtolower(trim($rowData[$attributeCode])), $options, true)) {`

---

Since the method `_getAttributeOptions` is only used for this anyway, I vote for option 2. This should be more performant as the array_map is not done over and over again. Do you agree?

**Comment by sprankhub** [comment]
@paales @avstudnitz any chance I get get the attention from one of you? I am happy to open a pull request with a solution as soon as we agreed on one of my suggestions. Thanks!

**Comment by cfroe** [comment]
Sorry leider kein Magento Experte ...

Am 12.02.2016 um 18:13 schrieb Simon Sprankel:
>
> @paales <https://github.com/paales> @avstudnitz 
> <https://github.com/avstudnitz> any chance I get get the attention 
> from one of you? I am happy to open a pull request with a solution as 
> soon as we agreed on one of my suggestions. Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/avstudnitz/AvS_FastSimpleImport/issues/233#issuecomment-183417286>.
>

-- 
Christoph Frömter

Amirada GmbH - Geschäftsstelle Freiburg
Nägeleseestr. 14
DE-79102 Freiburg

Tel:    +49 (0)761 / 13 76 555
E-Mail: c.froemter@amirada.com
Web:    www.amirada.com



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by avstudnitz** [comment]
@sprankhub Go ahead with option 2. Agree that the current handling is far from perfect. Thanks for caring!

**Comment by sprankhub** [comment]
Awesome, will do tomorrow! Since master is more current, I send the PR to the master branch if you do not wish anything else :)

**Comment by avstudnitz** [comment]
Use the develop branch please. It should be the same as master, except a merge commit perhaps. You can merge master into develop if needed.

**Comment by sprankhub** [comment]
This is fixed and can be closed.
