### ISSUE TITLE
Empty Fields Setting unset not empty fields

### ISSUE THREAD

**Issue by janziehme** [avstudnitz/AvS_FastSimpleImport#336]
Ho_Import: 1.7.0
AvS_FastSimpleImport: 0.7.0
ho_import_profile: catalog_category

Field Mapping of imported data is correct. Problem is, that all custom fields are empty after an import. If i change line 54 from

`$this->setUnsetEmptyFields(Mage::getStoreConfigFlag('fastsimpleimport/general/clear_field_on_empty_string'));`

to 

`$this->setUnsetEmptyFields(!Mage::getStoreConfigFlag('fastsimpleimport/general/clear_field_on_empty_string'));`

all data will be imported correctly.

In the configuration the setting clear_field_on_empty_string = No

**Comment by paales** [comment]
@janziehme Ik seems the configuration value is unclear what it should show.
https://github.com/avstudnitz/AvS_FastSimpleImport/pull/228

**Comment by ktruehl** [comment]
I debugged this problem. It looks like this problem occurrs if the import is from a CVS file and one of the attributes to be imported is a multi-select attribute and the value for this attribute contains more than one option.

For example for categories, consider the attribute `available_sort_by`. If you want to assign it the value `position,name,price` during the import, this will result in 3 rows for the default store. The first row containing `position` for this attribute, the second contains `name`, and the third `price`. However, for any non-multiselect attribute to be imported the second and third row will contain empty strings, since that's how the CVS is parsed.

Now consider the `_filterRowData()` method in the `AvS_FastSimpleImport_Model_Import_Entity_Category` and assume the `clear_field_on_empty_string` config parameter is set to `0` (which implies that `$this->_unsetEmptyFields` is `false`). For any non-multiselect attribute this method will not filter out the second and third rows, which contain empty strings. But this means that in the `_saveCategories()` method in the `foreach (array_intersect_key($rowData, $this->_attributes) as $attrCode => $attrValue)` loop the empty values in the second and third row will overwrite the valid value in the first row.

**Comment by ktruehl** [comment]
I opened a new issue for the problem I described, since it's not fixed. #361
